### ISSUE TITLE
Title of document 100 (requirements . . .)

### ISSUE THREAD

**Issue by sashahafner** [sashahafner/BMP-methods#10]
What should the title be? Currently it is "Requirements for measurement of biochemical methane potential (BMP)". Christof proposed including "validation criteria". If we also include recommendations in this document (issue #7) the title should reflect that also. Ideas?

**Comment by sashahafner** [comment]
How about "Guidelines for measurement of biochemical methane potential (BMP)"?

**Comment by ChristofHolliger** [comment]
I propose the following and made the changes in the document in this sense: 
"Requirements for measurement and validation of biochemical methane potential (BMP)"
One could even add "Compulsory" in front of the title to make it even stronger !

**Comment by koechl** [comment]
I agree to Christof and already made some comments in the file. It is still very short and compact, which is nice!
