### ISSUE TITLE
Review of document 100

### ISSUE THREAD

**Issue by sashahafner** [sashahafner/BMP-methods#13]
@core group, could you take a look and make edits directly in the tex file, or else in a downloaded pdf that you can later send to me? Anything that needs to be discussed can go here.

**Comment by koechl** [comment]
[100_requirements_Kk.pdf](https://github.com/sashahafner/BMP-methods/files/4359083/100_requirements_Kk.pdf)

**Comment by sashahafner** [comment]
Thanks @koechl! I'm working on these now.

**Comment by sashahafner** [comment]
Just incorporated suggestions in 9a0766f13af9b7d97e91f64304e1ed51b39c548a
