### ISSUE TITLE
Citations file

### ISSUE THREAD

**Issue by sashahafner** [sashahafner/BMP-methods#19]
We need to make it easy for users to cite these documents. This issue addressing how to do that.

**Comment by sashahafner** [comment]
For Zotero, the BibTeX file cite.bib seems to work, as long as the type is @ online. If @ misc is used, the entries are turned into books and the URLs are not exported in a bibliography. So this works:

```
@online{BMPdoc200BMP,
  title = {Calculation of {Biochemical} {Methane} {Potential} {(BMP)}. {Standard} {BMP} {Methods} document 200, version 1.6.},
  url = {https://www.dbfz.de/en/BMP},
  urldate = {2020-04-19},
  author = {Hafner, Sasha D. and Astals, Sergi and Holliger, Christof and Koch, Konrad and Weinrich, S{\"o}ren},
  year = {2020}
}
```

**Comment by sashahafner** [comment]
But @soweinrich found that Citavi doesn't import these URLs from the BibTeX file. It seems to be able to import RIS files: https://www1.citavi.com/sub/manual6/en/index.html?importing_other_formats.html . Can you try this file @soweinrich ?

https://github.com/sashahafner/BMP-methods/blob/revising/cite.ris

**Comment by soweinrich** [comment]
I tried to use the *.ris file, but the problem seems to remain the same. I am able to import all documents, but the URL (its called "online adress" in Citavi) is still missing. And again: If I manually add the URL in Citavi and then export to bibtex or RIS, the URL shows at the same place @sashahafner included it. However, if I import the same file (which I exported before), the URL is lost and not included in Citavi. Seems to be a strange behaviour...

Generally, we could also think of providing different options (file formats)?

**Comment by sashahafner** [comment]
Weird. We may not be able to solve this. But let's try different formats. I can create any of these using Zotero:

https://www.zotero.org/support/dev/data_formats

@soweinrich just let me know which ones you want to try.

**Comment by sashahafner** [comment]
This letter seems hard to fix too: ø. Working on it.

**Comment by sashahafner** [comment]
Can you try the new RIS file in revising commit a7e515ee5814495a13c684492425a6fc9046c79d ?

**Comment by soweinrich** [comment]
> 
> 
> Can you try the new RIS file in revising commit [a7e515e](https://github.com/sashahafner/BMP-methods/commit/a7e515ee5814495a13c684492425a6fc9046c79d) ?

Nope, does not work. Now all letters with accents are deleted (and not imported) entirely.

**Comment by soweinrich** [comment]
> 
> 
> Weird. We may not be able to solve this. But let's try different formats. I can create any of these using Zotero:
> 
> https://www.zotero.org/support/dev/data_formats
> 
> @soweinrich just let me know which ones you want to try.

Ok, from the standard import options we could try PubMed, EndNote and Web of Science. But it seems that you can export none of these in zotero. I manually added the import filters for MODS and RefWorks - maybe we try these two options?

**Comment by soweinrich** [comment]
I also tried all import and export options in Citavi itself, but it seems that the URL gets lost all the time (and sometimes also the document type is not exported correctly as well).

Maybe we should not consider import options for Citavi... But let's see, if some of the other formats will work eventually...
