### ISSUE TITLE
Format for citations

### ISSUE THREAD

**Issue by sashahafner** [sashahafner/BMP-methods#6]
We should make a recommendation for users.

**Comment by sashahafner** [comment]
How about this?

Hafner, S.D., Lojborg, N. 2019. Calculation of methane production from volumetric measurements. DBFZ BMP methods collection document 201, version 1.4. URL: https://github.com/sashahafner/BMP-methods. Accessed 28 Feb. 2020.

**Comment by sashahafner** [comment]
Also where should this go? Just in a separate doc that can be linked on DBFZ site? On the site itself perhaps? Or within each document as a footnote? I vote for the last option.

**Comment by sastals** [comment]
Why not to check an style which they can download? and provide the link somewhere.

I personally like Water Research and Bioresource Technology citation style.

**Comment by koechl** [comment]
We usually follow DIN ISO 690. I have only the German version available, but they also have examples for websites, for instance. I can share it with you and we can chose the most suitable one for us

**Comment by soweinrich** [comment]
I like the example from Sasha. But of course, we can follow a specific style or DIN

Generally, I would include this information in each document as a footnote in the beginning, using the same citation style applied in the document itself.

**Comment by sashahafner** [comment]
Here is the ISO 690 approach for a report:

![image](https://user-images.githubusercontent.com/35272876/76321565-974afd00-62b8-11ea-99f6-1f1b40bdc248.png)

and e-book:

![image](https://user-images.githubusercontent.com/35272876/76321673-b77abc00-62b8-11ea-9e49-6b624e06aea2.png)

and website:

![image](https://user-images.githubusercontent.com/35272876/76321730-cf524000-62b8-11ea-896b-f7daa5dfd659.png)

**Comment by sashahafner** [comment]
MDPI (thinking of it because of special issue) is similar for a website:

![image](https://user-images.githubusercontent.com/35272876/76322883-4f2cda00-62ba-11ea-8006-c8d0d23dc301.png)

**Comment by sashahafner** [comment]
OK how about this (for MDPI)?

Hafner, S.D., Lojborg, N. 2019. Calculation of Methane Production from Volumetric Measurements. Standard BMP Methods document 201, version 1.4. Available online: https://www.dbfz.de/en/BMP. (Accessed 28 Feb. 2020).

And we can provide BibTeX entry (can be imported into e.g., EndNote, so templates for any journal can be used):

@misc{BSM_d201_v1.4,
	title = {Calculation of {Methane} {Production} from {Volumetric} {Measurements}. {Standard} {BMP} {Methods} document 201, version 1.4},
	url = {https://www.dbfz.de/en/BMP},
	urldate = {2020-02-28},
	author = {Hafner, S. D. and Lojborg, N.},
	year = {2019}
}

A couple issues. . . apart from these documents essentially being self-published.

1. The document number and the version number need to be clear. So I think they need to be in the title section.
2. We should only provide one website. I think it should be DBFZ. In the documents themselves users can find the GitHub website.

**Comment by soweinrich** [comment]
Hm ok, "year published" appears twice in the Template of ISO 690. Despite of that the templates seem to include all information needed... Maybe use the website template with some modifications for stating the specific version and reference to "Standard BMP methods"  (since we cannot really name a Publisher or City). I still like your example (2,nd comment above).

**Comment by soweinrich** [comment]
ah, ok I didn't update and just saw your last comment. Yes, I like your last example! I agree, reference to Version number is necessary. Only citing one website is good as well - this way we already promote the Standard BMP methods website...

**Comment by sashahafner** [comment]
Ok great @soweinrich . Just a comment I started anyway:

> Maybe use the website template with some modifications for stating the specific version and reference to "Standard BMP methods" (since we cannot really name a Publisher or City).

BibTeX has a "journal" entry that could have "Standard BMP Methods" but it does not show up for all templates/style files (not for MDPI but yes for ISO 690). But even then the document/version numbers don't clearly fit anywhere. Unfortunately I think the best option is within the title block, which is a little awkward, but works.

**Comment by sashahafner** [comment]
Using the above BibTeX entry, this is what users would get (these are from Zotero):

MDPI:
1. Hafner, S.D.; Lojborg, N. Calculation of Methane Production from Volumetric Measurements. Standard BMP Methods document 201, version 1.4 Available online: https://www.dbfz.de/en/BMP (accessed on Feb 28, 2020).

ISO 690:
HAFNER, S. D. and LOJBORG, N., 2019. Calculation of Methane Production from Volumetric Measurements. Standard BMP Methods document 201, version 1.4. [online]. 2019. [Accessed 28 February 2020]. Available from: https://www.dbfz.de/en/BMP
(Yes, repeated date is odd.)

Elsevier:
Hafner, S.D., Lojborg, N., 2019. Calculation of Methane Production from Volumetric Measurements. Standard BMP Methods document 201, version 1.4 [WWW Document]. URL https://www.dbfz.de/en/BMP (accessed 2.28.20).

Good enough! Any remaining issues?

**Comment by sashahafner** [comment]
I will make a BibTeX file with citation info for all reports available on the GitHub repo, and we can add a link to the website, e.g., "Download a BibTeX file that can be imported into EndNote, Zotero, Mendeley, or other citation management programs to simplify citing these documents *here*." And we can include a suggested citation format on the site for those who don't use software.

**Comment by koechl** [comment]
This looks good to me. I think nowadays most people like to download the information to be processed by their reference management software, such as Zotero or Endnote.

**Comment by soweinrich** [comment]
Ok good. But it does not hurt to include an example on how to cite the individual document along with the download link to the Website...

**Comment by sashahafner** [comment]
> Ok good. But it does not hurt to include an example on how to cite the individual document along with the download link to the Website...

I agree. See issue #8 -- I will add a new version there in a minute. 

> Ok good. But it does not hurt to include an example on how to cite the individual document along with the download link to the Website...

Good. So they will have the choice.

Thanks for the input guys!

**Comment by sashahafner** [comment]
I meant. . .

> This looks good to me. I think nowadays most people like to download the information to be processed by their reference management software, such as Zotero or Endnote.

Good. So they will have the choice.

**Comment by sastals** [comment]
Guys,

No more comments from my end. I Agree!

BTW, how you make comments on old text?

**Comment by sashahafner** [comment]
Great. @sastals , just paste it after a ">" symbol of use the " button at the top. But I think you may have already figured it out.
