### ISSUE TITLE
Source info in docs

### ISSUE THREAD

**Issue by sashahafner** [sashahafner/BMP-methods#8]
Currently all the documents have info on the DBFZ site, file version, and document number in section 1. This issue is on sorting out the details for this section.

**Comment by sashahafner** [comment]
Does anyone have any concerns or suggestions about the current approach? Example below.

`
\section{DBFZ BMP methods collection}
Document number 100.
File version 1.1. 
This document is from the DBFZ BMP methods collection.
For more information, visit the site at \url{https://www.dbfz.de/en/BMP}.
`

It might be a bit odd to make it the first section. But I want it obvious, so people don't miss it. Should it be a footnote instead? Or just not have a section number? Also should we mention both the DBFZ site (kind of the main public interface for all these documents) only? Or also this GitHub repo? We could do this instead (footnote in title, plus GitHub info):

`
\footnote{
Document number 100.
File version 1.1. 
This document is from the DBFZ BMP methods collection.
For more information and other documents, visit the site at \url{https://www.dbfz.de/en/BMP}.
For version history or to propose changes to this document, visit \url{https://github.com/sashahafner/BMP-methods}.
}

Once we agree this will go in all documents.

**Comment by sashahafner** [comment]
@koechl no problem. Here is the question put more clearly. Currently each document starts with this section 1 message (see image). 

![Screenshot_2020-03-04 sashahafner BMP-methods](https://user-images.githubusercontent.com/35272876/75896940-c8818400-5e05-11ea-88f5-bb79093813d3.png)

**Comment by sashahafner** [comment]
And, in addition, what should it contain? I like the text in the footnote version. May seem like a trivial discussion, but this text will be on all documents and we should try to get it right from the start.

**Comment by soweinrich** [comment]
I would prefer a combination of both approaches:

I would state the origin and version (Document number 100, version 1.1 from Standard BMP Methods collection) below the list of authors (maybe in combination with the date). Not as a special section. Then add a footnote directly to this and add the text “For more information and other documents...” there.

**Comment by sashahafner** [comment]
Good idea. Here is the current draft based on this suggestion.

![image](https://user-images.githubusercontent.com/35272876/76236016-65775f00-6202-11ea-82b1-798cf92437d2.png)

**Comment by sastals** [comment]
I may prefer the last version. Nice in between. However, I do not have bad feelings about any of the options.

BTW, What is Anton Taboada doing here. He is a very nice guy! :)

**Comment by sashahafner** [comment]
New version. Any more comments?

![image](https://user-images.githubusercontent.com/35272876/76328014-20fec880-62c1-11ea-8c30-8f57c06599be.png)

**Comment by sashahafner** [comment]
> BTW, What is Anton Taboada doing here. He is a very nice guy! :)

Just one of the authors. I had not shown the whole page.

**Comment by sastals** [comment]
> Just one of the authors. I had not shown the whole page.

Nice!!! I just found out how to reply previous commnets :)

**Comment by soweinrich** [comment]
> New version. Any more comments?
> 
> ![image](https://user-images.githubusercontent.com/35272876/76328014-20fec880-62c1-11ea-8c30-8f57c06599be.png)

Actually, I would state the correct and full citation as an exmaple (with real names, version, etc.) in the first footnote and not just the structure ([authors], etc.). Otherwise, there might be some missunderstanding... I know, its a bit ugly with all the co-authors listed, but to avoid any confusion...

**Comment by sashahafner** [comment]
> Actually, I would state the correct and full citation as an exmaple (with real names, version, etc.) in the first footnote and not just the structure ([authors], etc.). 

You are right. I was being lazy and saving space.

**Comment by sashahafner** [comment]
Corrected now.
