### ISSUE TITLE
Authors on BMP calculations (document 200)

### ISSUE THREAD

**Issue by sashahafner** [sashahafner/BMP-methods#9]
The original version just had me as an author. It would be good to have more.

**Comment by sashahafner** [comment]
Who wants to be added? Please take a look, make/send any edits, and add yourself.

**Comment by koechl** [comment]
[200_BMP_calculations_Kk.pdf](https://github.com/sashahafner/BMP-methods/files/4359284/200_BMP_calculations_Kk.pdf)

**Comment by sashahafner** [comment]
Thanks @koechl . I missed this or forgot about it, but just made the changes now (and added you as co-author). See version 1.5 commit c4ad1ddf3c7e0de8aef04e14d8dcd5a00edbb5a0 . I am creating a new issue for your point about example calculations.

**Comment by sashahafner** [comment]
Core group is now on. Closing issue.
